global using FimiAppApi.Context;
global using FimiAppApi.Contracts;
global using FimiAppLibrary.Models;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Dapper;
global using System.Data;
global using Slapper;
global using System.ComponentModel.DataAnnotations;