global using FimiAppLibrary.Models;
global using FimiAppApi.Context;
global using FimiAppUI.Contracts;
global using Microsoft.AspNetCore.Components;
global using System.Net.Http.Json;
global using FimiAppUI.Services;
global using System.Net.Http;
global using static MudBlazor.Colors;
global using Microsoft.AspNetCore.Http;
global using System.Net.NetworkInformation;
global using System.Threading;
global using MudBlazor;
global using Microsoft.AspNetCore.Components.Web;
global using System.Text.RegularExpressions;
global using System.ComponentModel.DataAnnotations;
global using FluentValidation;
global using FimiAppUI.Validators;
global using System.Net;
global using static MudBlazor.CategoryTypes;
global using static MudBlazor.Defaults;
